dist: bionic
os: linux

language: python

compiler:
  - gcc

addons:
  apt:
    packages:
      - libgtk-3-dev

install:
  - pip install meson ninja   # use pip as version in repos < 0.49

script:
  - meson builddir && ninja -C builddir && meson test -C builddir
